src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bioguide_ID__c</fullName>
        <label>Bioguide ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
</CustomObject>

src/objects/Contact_Leg_junction__c.object
<CustomObject>
    <description>Relates Contacts to Legislation object with many to many relationship</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Legislation related to this Contact</relationshipLabel>
        <relationshipName>Contact_Leg_junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Legislation__c</fullName>
        <label>Legislation</label>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Contacts related to this Legislation</relationshipLabel>
        <relationshipName>Contact_Leg</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Key Ally</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supportive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-sponsor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Related to Legislation</label>
    <nameField>
        <displayFormat>ContLeg-{0000}</displayFormat>
        <label>Contact-Leg ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Related to Legislation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Corresponding_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Legislation1__c</fullName>
        <label>Legislation1</label>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Corresponding Bills 1</relationshipLabel>
        <relationshipName>Corresponding_Bill</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Legislation2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legislation2</label>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Corresponding Bills 2</relationshipLabel>
        <relationshipName>Corresponding_Bill2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Corresponding Bill</label>
    <nameField>
        <displayFormat>CorrLeg-{00000}</displayFormat>
        <label>Corresponding Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corresponding Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Legislation__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Id__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>unique id for congress</inlineHelpText>
        <label>Bill_Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <description>Just the numerical part of the bill or amendment number.</description>
        <inlineHelpText>Just the numerical part of the bill or amendment number.</inlineHelpText>
        <label>Bill Number</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_Prefix__c</fullName>
        <description>Bill prefix corresponding to bill title, e.g. &quot;HR&quot; for HR1212</description>
        <inlineHelpText>Bill prefix corresponding to bill title, e.g. &quot;HR&quot; for HR1212</inlineHelpText>
        <label>Bill Prefix</label>
        <picklist>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HJRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SJRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAMDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAMDT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bill_Title__c</fullName>
        <description>Title of proposed bill.  Leave out Bill Number (e.g. HR3254), which should go into Bill Number field.</description>
        <inlineHelpText>Title of proposed bill.  Leave out Bill Number (e.g. HR3254), which should go into Bill Number field.</inlineHelpText>
        <label>Bill Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Congressional_Session__c</fullName>
        <description>E.g. for the 112th congress select 112.  Must be filled in for Thomas link to work.</description>
        <inlineHelpText>E.g. for the 112th congress select 112.  Must be filled in for Thomas link to work.</inlineHelpText>
        <label>Congressional Session</label>
        <picklist>
            <picklistValues>
                <fullName>112</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>111</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>109</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cosponsors__c</fullName>
        <label>Cosponsors</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_Bill_Info_Updated__c</fullName>
        <description>When bill info was last pulled in from GovTrack</description>
        <inlineHelpText>When bill info was last pulled in from GovTrack</inlineHelpText>
        <label>Date Bill Info Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Introduced_Date__c</fullName>
        <description>Date the bill was introduced</description>
        <inlineHelpText>Date the bill was introduced</inlineHelpText>
        <label>Introduced Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_Major_Action__c</fullName>
        <label>Latest Major Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor_Info__c</fullName>
        <label>Sponsor Info</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Legislation</relationshipLabel>
        <relationshipName>Legislation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <description>CRS Summary</description>
        <inlineHelpText>CRS Summary</inlineHelpText>
        <label>Summary</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Legislation</label>
    <nameField>
        <label>Bill ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legislation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Legislator_Vote__c.object
<CustomObject>
    <fields>
        <fullName>Bill_Title__c</fullName>
        <formula>Roll_Vote__r.Legislation__r.Bill_Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bill Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Congressional_Session__c</fullName>
        <description>Congressional Session to which the bill belongs.  Set via workflow since it&apos;s used in a roll-up summary on Contact.  Won&apos;t be updated if the session is changed on the Legislation record after the Leg Vote record is created.</description>
        <inlineHelpText>Congressional Session to which the bill belongs.</inlineHelpText>
        <label>Congressional Session</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LegVoteId__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>concatenation of bioguide and roll id</inlineHelpText>
        <label>LegVoteId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Legislator__c</fullName>
        <label>Legislator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Legislator Votes</relationshipLabel>
        <relationshipName>Legislator_Votes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Roll_Vote__c</fullName>
        <label>Roll Vote</label>
        <referenceTo>Roll_Vote__c</referenceTo>
        <relationshipLabel>Legislator Votes</relationshipLabel>
        <relationshipName>Legislator_Votes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Vote__c</fullName>
        <label>Vote</label>
        <picklist>
            <picklistValues>
                <fullName>Yea</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Present</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Voting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Legislator Vote</label>
    <nameField>
        <displayFormat>LegVote-{00000}</displayFormat>
        <label>Legislator Vote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legislator Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Roll_Vote__c.object
<CustomObject>
    <fields>
        <fullName>Legislation__c</fullName>
        <label>Legislation</label>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Roll Votes</relationshipLabel>
        <relationshipName>Roll_Votes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <label>Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roll_Id__c</fullName>
        <externalId>true</externalId>
        <label>Roll Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Roll_Type__c</fullName>
        <label>Roll Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Roll Vote</label>
    <nameField>
        <label>Roll Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roll Votes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LegislationAction.cls
/*
 * Fetch details of the legislation with a web services callout and update the Legislation record
 *
 * WH, Exponent Partners, 2011
 */
public class LegislationAction {
       
    public static void getLegislationDetail(Legislation__c leg) {
        if (leg.Bill_Prefix__c != null && leg.Bill_Prefix__c.contains('AMDT')) {
            // amendment - remove 'ADMT' from prefix
            updateAmendmentDetail(leg.Id, leg.Bill_Prefix__c.substring(0,1).toLowerCase(), String.valueOf(leg.Bill_Number__c.setScale(0)), leg.Congressional_Session__c);
        } else {
            // bill
            updateBillDetail(leg.Id, leg.Bill_Prefix__c.toLowerCase(), String.valueOf(leg.Bill_Number__c.setScale(0)), leg.Congressional_Session__c);
            // votes
            updateBillVotes(leg.Id, leg.Bill_Prefix__c.toLowerCase(), String.valueOf(leg.Bill_Number__c.setScale(0)), leg.Congressional_Session__c);
        }
    }
    
    /*
     * Calling RTC amendments API
     */
    
    // Call out to the web services and gather info returned
    @future (callout=true)
    static void updateAmendmentDetail(Id legId, String amendmentPrefix, String amendmentNumber, String session) {
        
        Boolean doUpdate = false;
        String billId, purpose, status, lastAction, introducedAt, sponsorId;
        
        RealTimeCongressAPI api = new RealTimeCongressAPI();
        
        // Get officalTitle, shortTitle, status, lastAction, sponsorId, and cosponsorIds
        if (api.getAmendment(amendmentPrefix, amendmentNumber, session)) {
            doUpdate = true;
            String amendmentId = amendmentPrefix + amendmentNumber + '-' + session;
            billId = api.legDetailMap.get(amendmentId).billId;
            purpose = api.legDetailMap.get(amendmentId).getPurpose();
            status = api.legDetailMap.get(amendmentId).getStatus();
            lastAction = api.legDetailMap.get(amendmentId).getLastAction();
            introducedAt = api.legDetailMap.get(amendmentId).introducedAt;
            sponsorId = api.legDetailMap.get(amendmentId).sponsorId;
        }
        
        // Update the Legislation record
        if (doUpdate) {
            updateAmendmentRecord(legId, billId, purpose, status, lastAction, introducedAt, sponsorId);
        } else {
            System.debug('>>>>>>>>>> Callout to get amendment detail failed');
        }
    }
    
    // Update Legislation record with info returned from web services
    private static void updateAmendmentRecord(Id legId, String billId, String purpose, String status, String lastAction, String introducedAt, String sponsorId) {
        try {
            // Select Legislation record to update
            Legislation__c l = [select Id, Name, Bill_Id__c, Sponsor__c, (select Legislation1__c from Corresponding_Bill2__r) from Legislation__c where Id = :legId limit 1];
            
            if(billId!=null){
            	l.Name = billId;
            	l.bill_id__c = billId;
            }
            l.Bill_Title__c = (purpose != null  && purpose.length() > Legislation__c.Bill_Title__c.getDescribe().getLength()) ? purpose.substring(0, Legislation__c.Bill_Title__c.getDescribe().getLength()) : purpose;
            l.Status__c = (status != null  && status.length() > Legislation__c.Status__c.getDescribe().getLength()) ? status.substring(0, Legislation__c.Status__c.getDescribe().getLength()) : status;
            l.Latest_Major_Action__c = (lastAction != null  && lastAction.length() > Legislation__c.Latest_Major_Action__c.getDescribe().getLength()) ? lastAction.substring(0, Legislation__c.Latest_Major_Action__c.getDescribe().getLength()) : lastAction;
            // Convert date time string like 2011-02-10T12:00:00Z into a Date object
            l.Introduced_Date__c = (introducedAt != null) ? Date.valueOf(introducedAt.substring(0, introducedAt.indexOf('T'))) : null;
            l.Date_Bill_Info_Updated__c = System.now();
            
            // Look up sponsor by matching bioguide_id
            if (sponsorId != null) {
                List<Contact> sponsor = [select Id from Contact where Bioguide_ID__c = :sponsorId];
                l.Sponsor__c = (sponsor.size() > 0) ? sponsor[0].Id : null;
                l.Sponsor_Info__c = sponsorId;
            } else {
                l.Sponsor__c = null;
                l.Sponsor_Info__c = null;
            }
            
            // Insert junction to corresponding bill if not already there
            Corresponding_Bill__c relatedBillToInsert;
            
            // Get all existing corresponding bills
            //  Map Bill Id => corresponding bill junction
            Map<Id, Corresponding_Bill__c> relatedBillMap = new Map<Id, Corresponding_Bill__c>();
            for (Corresponding_Bill__c cb : l.Corresponding_Bill2__r) {
                relatedBillMap.put(cb.Legislation1__c, cb);
            }
            
            if (billId != null) {
                // Look up corresponding bill by matching billId
                billId = billId.toUpperCase(); // Legislation naming convention in SF uses prefix in upper case vs lower case in RTC API
                List<Legislation__c> relatedBills = [select Id from Legislation__c where Name = :billId];
                Id relatedBillId = (relatedBills.size() > 0) ? relatedBills[0].Id : null;
                
                if (relatedBillId != null) {
                    if (!relatedBillMap.containsKey(relatedBillId)) {
                        // Create new corresponding bill junction if none exists
                        relatedBillToInsert = new Corresponding_Bill__c(Legislation1__c = relatedBillId, Legislation2__c = legId);
                    } else {
                        // Reuse existing corresponding bill junction
                        relatedBillMap.remove(relatedBillId);
                    }
                }
            }
            
            if (relatedBillToInsert != null)
                insert relatedBillToInsert;
            
            // Corresponding bill junctions remaining in map are not related to the bill returned from web services
            if (!relatedBillMap.isEmpty())
                delete relatedBillMap.values();
        
            update l;
        
        } catch (Exception e) {
            System.debug('>>>>>>>>>> Update legislation failed: ' + e.getMessage());
            return;
        }
        
    }
    
    /*
     * Calling RTC bills API
     */
    
    // Call out to the web services and gather info returned
    @future (callout=true)
    static void updateBillDetail(Id legId, String billPrefix, String billNumber, String session) {
        
        Boolean doUpdate = false;
        String officialTitle, shortTitle, status, lastAction, summary, introducedAt, sponsorId;
        Set<String> cosponsorIds;
        String billId;
        
        RealTimeCongressAPI api = new RealTimeCongressAPI();
        
        // Get officalTitle, shortTitle, status, lastAction, sponsorId, and cosponsorIds
        if (api.getBill(billPrefix, billNumber, session)) {
            doUpdate = true;
            billId = billPrefix + billNumber + '-' + session;
            officialTitle = api.legDetailMap.get(billId).getOfficialTitle();
            shortTitle = api.legDetailMap.get(billId).getShortTitle();
            status = api.legDetailMap.get(billId).getStatus();
            lastAction = api.legDetailMap.get(billId).getLastAction();
            summary = api.legDetailMap.get(billId).summary;
            introducedAt = api.legDetailMap.get(billId).introducedAt;
            sponsorId = api.legDetailMap.get(billId).sponsorId;
            cosponsorIds = api.legDetailMap.get(billId).cosponsorIds;
        }
        
        // Update the Legislation record
        //  - use shortTitle if exists otherwise officialTitle
        if (doUpdate) {
            updateBillRecord(legId, billId, (shortTitle != null) ? shortTitle : officialTitle, status, lastAction, summary, introducedAt, sponsorId, cosponsorIds);
        } else {
            System.debug('>>>>>>>>>> Callout to get bill detail failed');
        }
    }
    
    // Call out to the web services and gather info returned
    @future (callout=true)
    static void updateBillVotes(Id legId, String billPrefix, String billNumber, String session) {
        
        Boolean doUpdate = false;
        String rollId, voteDate, result, voteType;
        RealTimeCongressAPI api = new RealTimeCongressAPI();
        List<Roll_Vote__c> rollVotes = new List<Roll_Vote__c>();
        // Get officalTitle, shortTitle, status, lastAction, sponsorId, and cosponsorIds
        if (api.getVotes(billPrefix, billNumber, session)) {
            doUpdate = true;
            for(String thisRollId : api.legDetailMap.keySet()){
                //Date dateVoted = date.newInstance(Integer.valueOf(api.legDetailMap.get(thisRollId).voted_at.substring(0,4)),Integer.valueOf(api.legDetailMap.get(thisRollId).voted_at.substring(5,2)),Integer.valueOf(api.legDetailMap.get(thisRollId).voted_at.substring(8,2)));
                Roll_Vote__c thisRollVote = new Roll_Vote__c(Legislation__c=legId, Name=api.legDetailMap.get(thisRollId).roll_id, Roll_Type__c=api.legDetailMap.get(thisRollId).roll_type,Roll_Id__c=api.legDetailMap.get(thisRollId).roll_id,Result__c=api.legDetailMap.get(thisRollId).result);
                rollVotes.add(thisRollVote);
                
            }

        }
        
        // Update the Legislation record
        //  - use shortTitle if exists otherwise officialTitle
        if (doUpdate) {
            upsert rollVotes Roll_Id__c;
            
            
            //soql the ids or the roll votes
            List<Roll_Vote__c> rollVotesAfterUpsert = [select id, roll_id__c from Roll_Vote__c where id IN :rollVotes];
            
            Map<String,Roll_Vote__c> rollIdToIdMap = new Map<String,Roll_Vote__c>();
            //put roll votes in a map of roll_id to id
            for(Roll_Vote__c thisRV : rollVotesAfterUpsert){
                rollIdToIdMap.put(thisRV.roll_id__c,thisRV);
            }
            
            //get the keyset of all the bioguide voter ids for this roll id
            
            Set<String> bioGuides = new Set<String>();
            for(String thisRollId : api.legDetailMap.keySet()){
                
                for(RealTimeCongressAPI.VoteInfo thisVoteInfo :api.legDetailMap.get(thisRollId).voterIdMap.get(thisRollId)){
                
                        bioGuides.add(thisVoteInfo.bioguide);
                }
                //voterIdMap.get(thisRollId);
            }
            //soql the contacts that are in that set
            List<Contact> legislators = [select id, Bioguide_ID__c from Contact where Bioguide_ID__c IN :bioGuides];
            Map<String, Contact> bioGuideContactMap = new Map<String, Contact>();
            
            for(Contact thisLeg : legislators){
                bioGuideContactMap.put(thisLeg.Bioguide_ID__c,thisLeg);
            }
            //put contacts in a map of roll_id to contact id
            
            List<Legislator_Vote__c> legVotes = new List<Legislator_Vote__c>();
            for(String thisRollId : api.legDetailMap.keySet()){
                for(RealTimeCongressAPI.VoteInfo thisVoteIfnfo: api.legDetailMap.get(thisRollId).voterIdMap.get(thisRollId)){
                    if(bioGuideContactMap.get(thisVoteIfnfo.bioguide)!=null){
                        String legVoteId = thisRollId+thisVoteIfnfo.bioguide;
                        Legislator_Vote__c thisLegVote = new Legislator_Vote__c();
                        
                        thisLegVote.Legislator__c=bioGuideContactMap.get(thisVoteIfnfo.bioguide).id;
                        thisLegVote.Roll_Vote__c=rollIdToIdMap.get(thisRollId).id;
                        thisLegVote.Vote__c=thisVoteIfnfo.vote;
                        thisLegVote.LegVoteId__c=legVoteId;
                        legVotes.add(thisLegVote);    
                    }
                }
                
            }
            
            upsert legVotes LegVoteId__c;
            
           // updateBillVotes(legId, (shortTitle != null) ? shortTitle : officialTitle, status, lastAction, summary, introducedAt, sponsorId, cosponsorIds);
        } else {
            System.debug('>>>>>>>>>> Callout to get bill detail failed');
        }
    }
    
    // Update Legislation record with info returned from web services
    private static void updateBillRecord(Id legId, String billId, String title, String status, String lastAction, String summary, String introducedAt, String sponsorId, Set<String> cosponsorIds) {
        try {
            // Select Legislation record to update
            Legislation__c l = [select Id, Name, bill_id__c,Sponsor__c, (select Contact__c, Role__c from Contact_Leg__r where Role__c = 'Co-sponsor') from Legislation__c where Id = :legId limit 1];
            if(billId!=null){
            	l.Name = billId;
            	l.bill_id__c = billId;
            }
            l.Bill_Title__c = (title != null  && title.length() > Legislation__c.Bill_Title__c.getDescribe().getLength()) ? title.substring(0, Legislation__c.Bill_Title__c.getDescribe().getLength()) : title;
            l.Status__c = (status != null  && status.length() > Legislation__c.Status__c.getDescribe().getLength()) ? status.substring(0, Legislation__c.Status__c.getDescribe().getLength()) : status;
            l.Latest_Major_Action__c = (lastAction != null  && lastAction.length() > Legislation__c.Latest_Major_Action__c.getDescribe().getLength()) ? lastAction.substring(0, Legislation__c.Latest_Major_Action__c.getDescribe().getLength()) : lastAction;
            l.Summary__c = summary;
            // Convert date time string like 2011-02-10T12:00:00Z into a Date object
            l.Introduced_Date__c = (introducedAt != null) ? Date.valueOf(introducedAt.substring(0, introducedAt.indexOf('T'))) : null;
            l.Date_Bill_Info_Updated__c = System.now();
            
            // Look up sponsor by matching bioguide_id
            if (sponsorId != null) {
                List<Contact> sponsor = [select Id from Contact where Bioguide_ID__c = :sponsorId];
                //if (sponsor.size() > 0) { l.Sponsor__c = sponsor[0].Id; } // Should be at most 1 contact
                l.Sponsor__c = (sponsor.size() > 0) ? sponsor[0].Id : null;
                l.Sponsor_Info__c = sponsorId;
            } else {
                l.Sponsor__c = null;
                l.Sponsor_Info__c = null;
            }
            
            // Look up cosponsors by matching bioguide_id
            List<Contact_Leg_junction__c> relatedContactsToInsert = new List<Contact_Leg_junction__c>();
            
            // Get all existing related Co-sponsor contacts
            Map<Id, Contact_Leg_junction__c> cosponsorMap = new Map<Id, Contact_Leg_junction__c>();
            for (Contact_Leg_junction__c clj : l.Contact_Leg__r) {
                cosponsorMap.put(clj.Contact__c, clj);
            }
            
            if (!cosponsorIds.isEmpty()) {
                for (Contact c: [select Id from Contact where Bioguide_ID__c in :cosponsorIds]) {
                    if (!cosponsorMap.containsKey(c.Id)) {
                        // Create new related contact if none exists
                        relatedContactsToInsert.add(new Contact_Leg_junction__c(Contact__c = c.Id, Legislation__c = legId, Role__c = 'Co-sponsor'));
                    } else {
                        // Reuse existing related contact
                        cosponsorMap.remove(c.Id);
                    }
                }
                
                String cosponsors = '';
                for (String ci : cosponsorIds) { cosponsors = cosponsors + ci + ', '; }
                l.Cosponsors__c = (cosponsors != '') ? cosponsors.subString(0, cosponsors.length()-2) : null;
            }
            
            if (!relatedContactsToInsert.isEmpty())
                insert relatedContactsToInsert;
            
            // Related contacts remaining in map are not in list of cosponsors returned from web services
            if (!cosponsorMap.isEmpty())
                delete cosponsorMap.values();
        
            // For debug purposes
            //l.Summary__c = Limits.getScriptStatements() + ' statements.';
            
            update l;
        
        } catch (Exception e) {
            System.debug('>>>>>>>>>> Update legislation failed: ' + e.getMessage());
            return;
        }
        
    }
    
   
    
    ////////// Unit Tests //////////
    
    static testMethod void testGetLegislationDetail() {
        Test.startTest();
        Legislation__c testBill = new Legislation__c(Bill_Prefix__c = 'S', Bill_Number__c = 614, Congressional_Session__c = '112');
        insert testBill;
        Test.stopTest();
        
        // Web services callout not executed in test
        Legislation__c insertedBill = [select Bill_Title__c, Cosponsors__c, Latest_Major_Action__c, Sponsor__c, Status__c from Legislation__c where Id = :testBill.Id limit 1];
        System.assertEquals(null, insertedBill.Bill_Title__c);
        System.assertEquals(null, insertedBill.Status__c);
        System.assertEquals(null, insertedBill.Latest_Major_Action__c);
        System.assertEquals(null, insertedBill.Sponsor__c);
        System.assertEquals(null, insertedBill.Cosponsors__c);
    }
    
    static testMethod void testUpdateAmendmentRecord() {
        Legislation__c testBill = new Legislation__c(Bill_Prefix__c = 'S', Bill_Number__c = 614, Congressional_Session__c = '112');
        insert testBill;
        
        Legislation__c testAnotherBill = new Legislation__c(Bill_Prefix__c = 'H', Bill_Number__c = 789, Congressional_Session__c = '112');
        insert testAnotherBill;
        
        Legislation__c testAmendment = new Legislation__c(Bill_Prefix__c = 'SAMDT', Bill_Number__c = 123, Congressional_Session__c = '112');
        insert testAmendment;
        
        Contact sponsor = new Contact(FirstName = 'Test', LastName = 'Sponsor', Bioguide_ID__c = 'S00001');
        insert sponsor;
        
        Corresponding_Bill__c cbjunction1 = new Corresponding_Bill__c(Legislation1__c = testBill.Id, Legislation2__c = testAmendment.Id);
        insert cbjunction1;
        
        Corresponding_Bill__c cbjunction2 = new Corresponding_Bill__c(Legislation1__c = testAnotherBill.Id, Legislation2__c = testAmendment.Id);
        insert cbjunction2;
        
        // Amendment related to testBill
        LegislationAction.updateAmendmentRecord(testAmendment.Id, 's614-112', 'To make it better', 'Passed', 'Amendment made to s614-112', '2011-12-01T14:00:00Z', 'S00001');
        
        Legislation__c updatedAmendment = [select Bill_Title__c, Latest_Major_Action__c, Introduced_Date__c, Date_Bill_Info_Updated__c, Sponsor__c, Sponsor_Info__c, Status__c from Legislation__c where Id = :testAmendment.Id limit 1];
        System.assertEquals('To make it better', updatedAmendment.Bill_Title__c);
        System.assertEquals('Passed', updatedAmendment.Status__c);
        System.assertEquals('Amendment made to s614-112', updatedAmendment.Latest_Major_Action__c);
        System.assertEquals('2011-12-01', String.valueOf(updatedAmendment.Introduced_Date__c));
        System.assertEquals(System.today().format(), updatedAmendment.Date_Bill_Info_Updated__c.date().format());
        System.assertEquals(sponsor.Id, updatedAmendment.Sponsor__c);
        System.assertEquals('S00001', updatedAmendment.Sponsor_Info__c);
        
        List<Corresponding_Bill__c> cbjuncts = [select Legislation1__c from Corresponding_Bill__c where Legislation2__c = :testAmendment.Id];
        // Old junction for testAnotherBill deleted, old junction for testBill kept
        System.assertEquals(1, cbjuncts.size());
        System.assertEquals(cbjunction1.Id, cbjuncts[0].Id);
        
        // Amendment related to testAnotherBill
        LegislationAction.updateAmendmentRecord(testAmendment.Id, 'h789-112', 'To make it even better', 'Passed', null, '2011-12-01T16:00:00Z', 'S00001');
        
        updatedAmendment = [select Bill_Title__c, Latest_Major_Action__c, Introduced_Date__c, Date_Bill_Info_Updated__c, Sponsor__c, Sponsor_Info__c, Status__c from Legislation__c where Id = :testAmendment.Id limit 1];
        System.assertEquals('To make it even better', updatedAmendment.Bill_Title__c);
        System.assertEquals('Passed', updatedAmendment.Status__c);
        System.assertEquals(null, updatedAmendment.Latest_Major_Action__c);
        System.assertEquals('2011-12-01', String.valueOf(updatedAmendment.Introduced_Date__c));
        System.assertEquals(System.today().format(), updatedAmendment.Date_Bill_Info_Updated__c.date().format());
        System.assertEquals(sponsor.Id, updatedAmendment.Sponsor__c);
        System.assertEquals('S00001', updatedAmendment.Sponsor_Info__c);
        
        cbjuncts = [select Legislation1__c from Corresponding_Bill__c where Legislation2__c = :testAmendment.Id];
        // Old junction for testBill deleted, new junction for testAnotherBill created
        System.assertEquals(1, cbjuncts.size());
        System.assertEquals(testAnotherBill.Id, cbjuncts[0].Legislation1__c);
    }
    
    static testMethod void testUpdateBillRecord() {
        Legislation__c testBill = new Legislation__c(Bill_Prefix__c = 'S', Bill_Number__c = 614, Congressional_Session__c = '112');
        insert testBill;
        
        Contact sponsor = new Contact(FirstName = 'Test', LastName = 'Sponsor', Bioguide_ID__c = 'S00001');
        insert sponsor;
        
        Contact[] cosponsors = new Contact[] {
            new Contact(FirstName = 'Test', LastName = 'Cosponsor 1', Bioguide_ID__c = 'CS00001'), 
            new Contact(FirstName = 'Test', LastName = 'Cosponsor 2', Bioguide_ID__c = 'CS00077'), 
            new Contact(FirstName = 'Test', LastName = 'Cosponsor 3', Bioguide_ID__c = 'CS00099')
        };
        insert cosponsors;
        
        Contact_Leg_junction__c csjunction1 = new Contact_Leg_junction__c(Contact__c = cosponsors[0].Id, Legislation__c = testBill.Id, Role__c = 'Co-sponsor');
        insert csjunction1;
        
        Contact_Leg_junction__c csjunction2 = new Contact_Leg_junction__c(Contact__c = cosponsors[1].Id, Legislation__c = testBill.Id, Role__c = 'Co-sponsor');
        insert csjunction2;
        
        Contact_Leg_junction__c otherjunction = new Contact_Leg_junction__c(Contact__c = cosponsors[0].Id, Legislation__c = testBill.Id, Role__c = 'Other');
        insert otherjunction;
        
        LegislationAction.updateBillRecord(testBill.Id, 'H.R.5652-112','Test title', 'Pending President signature', 'Passed in Senate', 'Great summary', '2011-02-10T12:00:00Z', 'S00001', new Set<String> { 'CS00077', 'CS00099' });
        
        Legislation__c updatedBill = [select Bill_Title__c, Cosponsors__c, Latest_Major_Action__c, Summary__c, Introduced_Date__c, Date_Bill_Info_Updated__c, Sponsor__c, Sponsor_Info__c, Status__c from Legislation__c where Id = :testBill.Id limit 1];
        System.assertEquals('Test title', updatedBill.Bill_Title__c);
        System.assertEquals('Pending President signature', updatedBill.Status__c);
        System.assertEquals('Passed in Senate', updatedBill.Latest_Major_Action__c);
        System.assertEquals('Great summary', updatedBill.Summary__c);
        System.assertEquals('2011-02-10', String.valueOf(updatedBill.Introduced_Date__c));
        System.assertEquals(System.today().format(), updatedBill.Date_Bill_Info_Updated__c.date().format());
        System.assertEquals(sponsor.Id, updatedBill.Sponsor__c);
        System.assertEquals('S00001', updatedBill.Sponsor_Info__c);
        System.assertEquals(true, updatedBill.Cosponsors__c.contains('CS00077'));
        System.assertEquals(true, updatedBill.Cosponsors__c.contains('CS00099'));
        
        List<Contact_Leg_junction__c> csjuncts = new List<Contact_Leg_junction__c>();
        List<Contact_Leg_junction__c> otherjuncts = new List<Contact_Leg_junction__c>();
        for (Contact_Leg_junction__c clj : [select Contact__c, Role__c from Contact_Leg_junction__c where Legislation__c = :testBill.Id]) {
            if (clj.Role__c == 'Co-sponsor')
                csjuncts.add(clj);
            else
                otherjuncts.add(clj);
        }
        // Old cosponsor junction for cosponsors[0] deleted, old junction for cosponsors[1] kept, 1 new junction for cosponsors[2] inserted
        System.assertEquals(2, csjuncts.size());
        if (csjuncts[0].Contact__c == cosponsors[1].Id) {
            System.assertEquals(csjunction2.Id, csjuncts[0].Id);    // old junction for cosponsors[1]
            System.assertEquals(cosponsors[2].Id, csjuncts[1].Contact__c);
        } else {
            System.assertEquals(cosponsors[2].Id, csjuncts[0].Contact__c);
            System.assertEquals(csjunction2.Id, csjuncts[1].Id);    // old junction for cosponsors[1]
            System.assertEquals(cosponsors[1].Id, csjuncts[1].Contact__c);
        }
        // Other junction unchanged
        System.assertEquals(1, otherjuncts.size());
        System.assertEquals(otherjunction.Id, otherjuncts[0].Id);
    }
    
}