src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bioguide_ID__c</fullName>
        <label>Bioguide ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    
</CustomObject>

src/objects/Contact_Leg_junction__c.object
<CustomObject>
    <description>Relates Contacts to Legislation object with many to many relationship</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Legislation related to this Contact</relationshipLabel>
        <relationshipName>Contact_Leg_junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Legislation__c</fullName>
        <label>Legislation</label>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Contacts related to this Legislation</relationshipLabel>
        <relationshipName>Contact_Leg</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Key Ally</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supportive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-sponsor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Related to Legislation</label>
    <nameField>
        <displayFormat>ContLeg-{0000}</displayFormat>
        <label>Contact-Leg ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contacts Related to Legislation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Corresponding_Bill__c.object
<CustomObject>
    <fields>
        <fullName>Legislation1__c</fullName>
        <label>Legislation1</label>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Corresponding Bills 1</relationshipLabel>
        <relationshipName>Corresponding_Bill</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Legislation2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legislation2</label>
        <referenceTo>Legislation__c</referenceTo>
        <relationshipLabel>Corresponding Bills 2</relationshipLabel>
        <relationshipName>Corresponding_Bill2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Corresponding Bill</label>
    <nameField>
        <displayFormat>CorrLeg-{00000}</displayFormat>
        <label>Corresponding Bill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Corresponding Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Legislation__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether IAVA is currently tracking this bill</description>
        <inlineHelpText>Whether IAVA is currently tracking this bill</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <description>Just the numerical part of the bill or amendment number.</description>
        <inlineHelpText>Just the numerical part of the bill or amendment number.</inlineHelpText>
        <label>Bill Number</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_Prefix__c</fullName>
        <description>Bill prefix corresponding to bill title, e.g. &quot;HR&quot; for HR1212</description>
        <inlineHelpText>Bill prefix corresponding to bill title, e.g. &quot;HR&quot; for HR1212</inlineHelpText>
        <label>Bill Prefix</label>
        <picklist>
            <picklistValues>
                <fullName>HR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HJRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HCRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SJRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SCRES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HAMDT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SAMDT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Bill_Title__c</fullName>
        <description>Title of proposed bill.  Leave out Bill Number (e.g. HR3254), which should go into Bill Number field.</description>
        <inlineHelpText>Title of proposed bill.  Leave out Bill Number (e.g. HR3254), which should go into Bill Number field.</inlineHelpText>
        <label>Bill Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Congressional_Session__c</fullName>
        <description>E.g. for the 112th congress select 112.  Must be filled in for Thomas link to work.</description>
        <inlineHelpText>E.g. for the 112th congress select 112.  Must be filled in for Thomas link to work.</inlineHelpText>
        <label>Congressional Session</label>
        <picklist>
            <picklistValues>
                <fullName>112</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>111</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>110</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>109</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_Bill_Info_Updated__c</fullName>
        <description>When bill info was last pulled in from GovTrack</description>
        <inlineHelpText>When bill info was last pulled in from GovTrack</inlineHelpText>
        <label>Date Bill Info Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Introduced_Date__c</fullName>
        <description>Date the bill was introduced</description>
        <inlineHelpText>Date the bill was introduced</inlineHelpText>
        <label>Introduced Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_Major_Action__c</fullName>
        <label>Latest Major Action</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Legislation</relationshipLabel>
        <relationshipName>Legislation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <description>CRS Summary</description>
        <inlineHelpText>CRS Summary</inlineHelpText>
        <label>Summary</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Legislation</label>
    <nameField>
        <label>Bill ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legislation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LegislationUpdateBatchableTest.cls
/*
    Copyright (c) 2009, Salesforce.com Foundation
    All rights reserved.
    
    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Salesforce.com Foundation nor the names of
      its contributors may be used to endorse or promote products derived
      from this software without specific prior written permission.
 
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
    "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
    FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE 
    COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, 
    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
    CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
    LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN 
    ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
    POSSIBILITY OF SUCH DAMAGE.
*/
/**
 * Test LegislationUpdateBatchable.cls
 */
@isTest
private class LegislationUpdateBatchableTest {

	static testMethod void testBatchUpdateAmendmentRecords() {
		
		// Set up legislator contacts and legislation
		List<Contact> reps = new List<Contact> {
			new Contact(FirstName = 'Test', LastName = 'Legislator 0', Bioguide_ID__c = 'H0001'),	// Sponsor for 's246-112'
			new Contact(FirstName = 'Test', LastName = 'Legislator 1', Bioguide_ID__c = 'H0002'),	// Sponsor for 'h468-112'
			new Contact(FirstName = 'Test', LastName = 'Legislator 2', Bioguide_ID__c = 'S0003'),
			new Contact(FirstName = 'Test', LastName = 'Legislator 3')
		};
		insert reps;
		
		// Active bill #1
		Legislation__c bill1 = new Legislation__c(Active__c = true, Name = 'S123-112', Bill_Prefix__c = 'S', Bill_Number__c = 123, Congressional_Session__c = '112');
		insert bill1;
		
		// Active bill #2
		Legislation__c bill2 = new Legislation__c(Active__c = true, Name = 'HR234-112', Bill_Prefix__c = 'HR', Bill_Number__c = 234, Congressional_Session__c = '112');
		insert bill2;
		
		// Active amendment #1 (related to bill #1) that will be updated - update Sponsor to reps[0], delete corresponding bill junction cbs[1] to bill2
		Legislation__c amend1 = new Legislation__c(Active__c = true, Name = 'SAMDT246-112', Bill_Prefix__c = 'SAMDT', Bill_Number__c = 246, Congressional_Session__c = '112', Sponsor__c = reps[3].Id);
		insert amend1;
		
		// Active amendment #2 (related to bill #2) that will be updated - update Sponsor to reps[1], insert corresponding bill junction to bill2
		Legislation__c amend2 = new Legislation__c(Active__c = true, Name = 'HAMDT468-112', Bill_Prefix__c = 'HAMDT', Bill_Number__c = 468, Congressional_Session__c = '112');
		insert amend2;
		
		// Pre-existing corresponding bill junction records
		List<Corresponding_Bill__c> cbs = new List<Corresponding_Bill__c> {
			new Corresponding_Bill__c(Legislation1__c = bill1.Id, Legislation2__c = amend1.Id),		// keep this matched bill junction
			new Corresponding_Bill__c(Legislation1__c = bill2.Id, Legislation2__c = amend1.Id)		// remove this unmatched bill junction
		};
		insert cbs;
		
		// Set up fake Real Time Congress API response for bills
		RealTimeCongressAPI api = new RealTimeCongressAPI();
		api.recordCount = 2;
		api.legislators = new Set<String> { 'H0001', 'H0002' };
		RealTimeCongressAPI.LegInfo amendmentInfo1 = new RealTimeCongressAPI.LegInfo('s246-112', 's123-112', 'Status 1', 'Purpose 1', 'Last action 1', '2011-12-01T14:00:00Z', 'H0001');
		RealTimeCongressAPI.LegInfo amendmentInfo2 = new RealTimeCongressAPI.LegInfo('h468-112', 'hr234-112', 'Status 2', 'Purpose 2', null, null, 'H0002');
		api.legDetailMap = new Map<String, RealTimeCongressAPI.LegInfo> { 's246-112' => amendmentInfo1, 'h468-112' => amendmentInfo2 };
		
		// Test batchUpdateAmendmentRecords()
		Test.startTest();
		LegislationUpdateBatchable.batchUpdateAmendmentRecords(new List<sObject> { amend1, amend2 }, api);
		Test.stopTest();
		
		Legislation__c leg = [select Bill_Title__c, Status__c, Latest_Major_Action__c, Introduced_Date__c, Date_Bill_Info_Updated__c, Sponsor__c from Legislation__c where Id = :amend1.Id];
		
		System.assertEquals('Purpose 1', leg.Bill_Title__c);
		System.assertEquals('Status 1', leg.Status__c);
		System.assertEquals('Last action 1', leg.Latest_Major_Action__c);
		System.assertEquals('2011-12-01', String.valueOf(leg.Introduced_Date__c));
		System.assertEquals(System.today().format(), leg.Date_Bill_Info_Updated__c.date().format());
		System.assertEquals(reps[0].Id, leg.Sponsor__c);
		
		// 1 matched junction kept, 1 unmatched junction deleted
		List<Corresponding_Bill__c> cbjunctions = [select Id, Legislation1__c from Corresponding_Bill__c where Legislation2__c = :amend1.Id];
		
		System.assertEquals(1, cbjunctions.size());
		System.assertEquals(cbs[0].Id, cbjunctions[0].Id);				// matched junction kept
		System.assertEquals(bill1.Id, cbjunctions[0].Legislation1__c);	// kept junction unchanged
		
		leg = [select Bill_Title__c, Status__c, Latest_Major_Action__c, Introduced_Date__c, Date_Bill_Info_Updated__c, Sponsor__c from Legislation__c where Id = :amend2.Id];
		
		System.assertEquals('Purpose 2', leg.Bill_Title__c);
		System.assertEquals('Status 2', leg.Status__c);
		System.assertEquals(null, leg.Latest_Major_Action__c);
		System.assertEquals(null, String.valueOf(leg.Introduced_Date__c));
		System.assertEquals(System.today().format(), leg.Date_Bill_Info_Updated__c.date().format());
		System.assertEquals(reps[1].Id, leg.Sponsor__c);
		
		// 1 new junction inserted
		cbjunctions = [select Id, Legislation1__c from Corresponding_Bill__c where Legislation2__c = :amend2.Id];
		
		System.assertEquals(1, cbjunctions.size());
		System.assertEquals(bill2.Id, cbjunctions[0].Legislation1__c);
	}
	
	static testMethod void testBatchUpdateBillRecords() {
		
		// Set up legislator contacts and legislation
		List<Contact> reps = new List<Contact> {
			new Contact(FirstName = 'Test', LastName = 'Legislator 0', Bioguide_ID__c = 'H0001'),	// Sponsor for 'hr123-112'
			new Contact(FirstName = 'Test', LastName = 'Legislator 1', Bioguide_ID__c = 'H0002'),	// Co-sponsor for 'hr123-112'
			new Contact(FirstName = 'Test', LastName = 'Legislator 2', Bioguide_ID__c = 'S0003'),	// Co-sponsor for 'hr123-112'
			new Contact(FirstName = 'Test', LastName = 'Legislator 3')
		};
		insert reps;
		
		// Active bill that will be updated - update Sponsor to reps[0], add missing co-sponsor reps[1], delete co-sponsor junction cljs[0]
		Legislation__c bill1 = new Legislation__c(Active__c = true, Name = 'HR123-112', Bill_Prefix__c = 'HR', Bill_Number__c = 123, Congressional_Session__c = '112', Sponsor__c = reps[3].Id);
		insert bill1;
		
		// Pre-existing contact legislation junction records
		List<Contact_Leg_junction__c> cljs = new List<Contact_Leg_junction__c> {
			new Contact_Leg_junction__c(Contact__c = reps[0].Id, Legislation__c = bill1.Id, Role__c = 'Co-sponsor'),		// remove this co-sponsor
			new Contact_Leg_junction__c(Contact__c = reps[2].Id, Legislation__c = bill1.Id, Role__c = 'Co-sponsor'),		// keep this co-sponsor
			new Contact_Leg_junction__c(Contact__c = reps[3].Id, Legislation__c = bill1.Id, Role__c = 'Other')			// keep this non-cosponsor
		};
		insert cljs;
		
		// Active bill that will be updated - use official title when there is no short title
		Legislation__c bill2 = new Legislation__c(Active__c = true, Name = 'S456-112', Bill_Prefix__c = 'S', Bill_Number__c = 456, Congressional_Session__c = '112');
		insert bill2;
		
		// Set up fake Real Time Congress API response for bills
		RealTimeCongressAPI api = new RealTimeCongressAPI();
		api.recordCount = 2;
		api.legislators = new Set<String> { 'H0001', 'H0002', 'S0003' };
		RealTimeCongressAPI.LegInfo billInfo1 = new RealTimeCongressAPI.LegInfo('hr123-112', 'Passed in House', 'Test House Bill Official', 'Test House Bill Short', 'Sent to Senate', 'Great summary', '2011-02-10T12:00:00Z', 
			'H0001', new Set<String> { 'H0002', 'S0003' });
		RealTimeCongressAPI.LegInfo billInfo2 = new RealTimeCongressAPI.LegInfo('s456-112', 'Voted in Senate', 'Test Senate Bill Official', null, null, null, null, null, null);
		api.legDetailMap = new Map<String, RealTimeCongressAPI.LegInfo> { 'hr123-112' => billInfo1, 's456-112' => billInfo2 };
		
		// Test batchUpdateBillRecords()
		Test.startTest();
		LegislationUpdateBatchable.batchUpdateBillRecords(new List<sObject> { bill1, bill2 }, api);
		Test.stopTest();
		
		Legislation__c leg = [select Bill_Title__c, Status__c, Latest_Major_Action__c, Summary__c, Introduced_Date__c, Date_Bill_Info_Updated__c, Sponsor__c from Legislation__c where Id = :bill1.Id];
		
		System.assertEquals('Test House Bill Short', leg.Bill_Title__c);
		System.assertEquals('Passed in House', leg.Status__c);
		System.assertEquals('Sent to Senate', leg.Latest_Major_Action__c);
		System.assertEquals('Great summary', leg.Summary__c);
		System.assertEquals('2011-02-10', String.valueOf(leg.Introduced_Date__c));
		System.assertEquals(System.today().format(), leg.Date_Bill_Info_Updated__c.date().format());
		System.assertEquals(reps[0].Id, leg.Sponsor__c);
		
		List<Contact_Leg_junction__c> cljunctions = [select Contact__c, Role__c from Contact_Leg_junction__c where Legislation__c = :bill1.Id];
		
		System.assertEquals(3, cljunctions.size());
		for (Contact_Leg_junction__c cj : cljunctions) {
			if (cj.Role__c == 'Co-sponsor') {
				// New junction for reps[1] inserted'; existing junction cljs[1] for reps[2] kept; old junction cljs[0] for reps[0] removed
				if (cj.Id != cljs[1].Id) {
					System.assertNotEquals(cljs[0].Id, cj.Id);
					System.assertEquals(reps[1].Id, cj.Contact__c);
				}
			} else {
				// 'Other' junction kept intact
				System.assertEquals(reps[3].Id, cj.Contact__c);
				System.assertEquals('Other', cj.Role__c);
			}
		}
		
		leg = [select Bill_Title__c, Status__c, Latest_Major_Action__c, Summary__c, Introduced_Date__c, Date_Bill_Info_Updated__c, Sponsor__c from Legislation__c where Id = :bill2.Id];
		
		System.assertEquals('Test Senate Bill Official', leg.Bill_Title__c);
		System.assertEquals('Voted in Senate', leg.Status__c);
		System.assertEquals(null, leg.Latest_Major_Action__c);
		System.assertEquals(null, leg.Summary__c);
		System.assertEquals(null, String.valueOf(leg.Introduced_Date__c));
		System.assertEquals(System.today().format(), leg.Date_Bill_Info_Updated__c.date().format());
		System.assertEquals(null, leg.Sponsor__c);
		
		cljunctions = [select Contact__c, Role__c from Contact_Leg_junction__c where Legislation__c = :bill2.Id];
		
		System.assertEquals(0, cljunctions.size());
	}
}