src/objects/Legislation__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Whether IAVA is currently tracking this bill</description>
        <inlineHelpText>Whether IAVA is currently tracking this bill</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Legislation</label>
    <nameField>
        <label>Bill ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legislation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LegislationUpdateControllerExt.cls
public class LegislationUpdateControllerExt {
	
	private static Legislation__c legislation;
	
	public LegislationUpdateControllerExt(ApexPages.StandardController controller) {
		legislation = (Legislation__c)controller.getRecord();
	}
	
	public PageReference refresh() {
		if (legislation.Active__c)
			LegislationAction.getLegislationDetail(legislation);
		return new PageReference('/' + legislation.Id);
		//return new PageReference('/a0y/o');
	}
}